/*
    ==============================================================================
    JUCE Plugin Definitions
    ==============================================================================
    This file contains additional JUCE plugin macros that may not be
    defined by JUCE's CMake build system.
*/

#pragma once

//==============================================================================
// NOTE: Most plugin definitions are generated by JUCE's juce_add_plugin()
// in CMakeLists.txt. This file only contains definitions that JUCE doesn't
// automatically generate.
//==============================================================================

//==============================================================================
// Plugin Identification (for reference, overridden by CMake)
// #define JucePlugin_ManufacturerCode  0x57485452  // CMake generates this
// #define JucePlugin_PluginCode          0x57485042  // CMake generates this

//==============================================================================
// Additional Plugin Metadata
#ifndef JucePlugin_Desc
#define JucePlugin_Desc  "Virtual pedalboard with 10 guitar effects"
#endif

//==============================================================================
// VST3 Category
#ifndef JucePlugin_VST3Category
#define JucePlugin_VST3Category  "Fx|Modulation"
#endif

//==============================================================================
// LV2 URI
#ifndef JucePlugin_LV2URI
#define JucePlugin_LV2URI  "https://whiteroom.audio/plugins/WhiteRoomPedalboard"
#endif

