name: WhiteRoomiOS
options:
  bundleIdPrefix: com.whiteroom
  deploymentTarget:
    iOS: "15.0"
targets:
  WhiteRoomiOS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: WhiteRoomiOSApp
        includes: [ "*.swift" ]
      - path: SwiftFrontendShared
        includes: [ "**/*.swift" ]
        excludes:
          - "Tests/**"
      - path: WhiteRoomiOS/Sources/SwiftFrontendCore
        includes: [ "**/*.swift" ]
        excludes:
          - "UI/Components/macOS/SongCard.swift"  # Duplicate of SwiftFrontendShared version
    info:
      path: WhiteRoomiOSApp/Info.plist
      properties:
        CFBundleDisplayName: White Room
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.whiteroom.ios
      SWIFT_VERSION: "5.7"
      TARGETED_DEVICE_FAMILY: "1,2"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
schemes:
  WhiteRoomiOS:
    build:
      targets:
        WhiteRoomiOS: all
    run:
      config: Debug
    archive:
      config: Release
