name: WhiteRoomiOS
options:
  bundleIdPrefix: com.whiteroom
  developmentLanguage: en
  createIntermediateGroups: true
  defaultConfig: Debug
  settings:
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGN_IDENTITY: ""
    ENABLE_PREVIEWS: YES

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.0.0

targets:
  WhiteRoomiOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: ../Sources
        includes: [ "*.swift" ]
      - path: ../Sources
        excludes: [
          "Info.plist"
        ]
      - path: ../../SwiftFrontendShared
        includes: [ "**/*.swift" ]
        excludes: [
          "Tests/**",
          "Repositories/BackupRepository.swift",
          "Repositories/MixGraphRepository.swift",
          "Repositories/UserRepository.swift",
          "Repositories/PerformanceRepository.swift",
          "Components/Cards/SongCard.swift"
        ]
    dependencies:
      - package: GRDB
        product: GRDB
    info:
      path: ../Sources/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortraitUpsideDown
        UILaunchScreen: {}
    settings:
      BASE_PATH: ../
      PRODUCT_BUNDLE_IDENTIFIER: com.bretbouchard.WhiteRoomiOS
      PRODUCT_NAME: WhiteRoomiOS
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: ""
      GENERATE_INFOPLIST_FILE: YES
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      SUPPORTED_PLATFORMS: iphoneos
      SDKROOT: iphoneos
      TARGETED_DEVICE_FAMILY: "1,2"
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      ONLY_ACTIVE_ARCH: NO
      SUPPORTS_MACCATALYST: NO

  SwiftFrontendCoreTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: ../Tests
        includes: [ "*.swift" ]
    dependencies:
      - target: WhiteRoomiOS
        link: false
    settings:
      BASE_PATH: ../
      SWIFT_VERSION: "5.9"
      ENABLE_TESTABILITY: YES
      GENERATE_INFOPLIST_FILE: YES
