/*
  JUCE Compilation Info

  JUCE expects these symbols to be defined at link time.
  They are normally generated by JUCE's build tools (jucer).
*/

namespace juce
{
    extern const char* juce_compilationDate = __DATE__;
    extern const char* juce_compilationTime = __TIME__;
}
