/**
 * Native binding loader
 *
 * Loads the compiled NAPI addon. This file will be generated by node-gyp
 * in the build/Release directory.
 */

import path from "path";

// Try to load the native addon
let bindings: any;

try {
  // Load the prebuilt native addon from build/Release
  const addonPath = path.join(
    __dirname,
    "../build/Release/white_room_ffi.node",
  );
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  bindings = require(addonPath);
} catch (e) {
  // Fallback: try loading from Debug build
  try {
    const addonPath = path.join(
      __dirname,
      "../build/Debug/white_room_ffi.node",
    );
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    bindings = require(addonPath);
  } catch (e2) {
    throw new Error(
      "Failed to load native addon. Make sure to run `npm run build` first.\n" +
        "Original error: " +
        (e as Error).message,
    );
  }
}

export default bindings;
